### ISSUE TITLE
[Feature] Add `debug_` macro variants

### ISSUE THREAD

**Issue by aloucks** [ohsayan/all_asserts#2]
## Feature
It would be nice if there were `debug_` variants of all the macros. (e.g. `debug_assert_le`)

## Impact
This would allow the assertion to be compiled out in release builds (e.g. just like with `std::debug_assert_eq`).

**Comment by ohsayan** [comment]
That's a fantastic idea! Would you have the time to work on it?; I can assign you then. Otherwise, I'll get it done.

NVM, I've created a PR for it already :)

**Comment by ohsayan** [comment]
@aloucks, I am about to merge the PR; tell me if you need anything else :)

**Comment by aloucks** [comment]
@ohsayan Looks great, thank you!

**Comment by ohsayan** [comment]
Merged and done; will publish release in a while
